/**/forward_keyboard:
  ros__parameters:
    velocity_scales:
      translation:
        x: 0.2
        y: 0.2
        z: 0.2
      rotation:
        x: 0.2
        y: 0.2
        z: 0.2
      joints:
        - 0.2
        - 0.2
        - 0.2
        - 0.2
        - 0.2
        - 0.2
        - 0.2
    keyboard_layout:
      # uses pynput: https://pypi.org/project/pynput/
      translation:
        x:
          increase: "w"
          decrease: "s"
        y:
          increase: "a"
          decrease: "d"
        z:
          increase: "Key.up"
          decrease: "Key.down"
      rotation:
        x:
          increase: "u"
          decrease: "j"
        y:
          increase: "h"
          decrease: "k"
        z:
          increase: "Key.left"
          decrease: "Key.right"
      joints:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
      escape: "Key.esc"
      pause: "p"
      reverse_joints: "r"
