# Use of /** so that the configurations hold for controller
# managers regardless of their namespace. Useful in multi-robot setups.
/**/controller_manager:
  ros__parameters:
    update_rate: 1000

    # ROS 2 control broadcasters
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    force_torque_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # LBR ROS 2 control broadcasters
    lbr_state_broadcaster:
      type: lbr_ros2_control/LBRStateBroadcaster

    # ROS 2 control controllers
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    # LBR ROS 2 control controllers
    lbr_joint_position_command_controller:
      type: lbr_ros2_control/LBRJointPositionCommandController

    lbr_torque_command_controller:
      type: lbr_ros2_control/LBRTorqueCommandController

    lbr_wrench_command_controller:
      type: lbr_ros2_control/LBRWrenchCommandController

    # Admittance controller
    admittance_controller:
      type: lbr_ros2_control/AdmittanceController

    # Boolean I/O Controller
    boolean_io_controller:
      type: io_controllers/BooleanIOController

    # Digital I/O Controller
    digital_io_controller:
      type: io_controllers/DigitalIOController

    # Analog I/O Controller
    analog_io_controller:
      type: io_controllers/AnalogIOController

/**/force_torque_broadcaster:
  ros__parameters:
    frame_id: lbr/link_tool # namespace: https://github.com/ros2/rviz/issues/1103
    sensor_name: estimated_ft_sensor

/**/joint_trajectory_controller:
  ros__parameters:
    joints:
      - A1
      - A2
      - A3
      - A4
      - A5
      - A6
      - A7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

/**/forward_position_controller:
  ros__parameters:
    joints:
      - A1
      - A2
      - A3
      - A4
      - A5
      - A6
      - A7
    interface_name: position

/**/boolean_io_controller:
  ros__parameters:
    io_names:
      - boolean_io_0
      - boolean_io_1
    command_interfaces:
      - command
    state_interfaces:
      - state
    state_publish_rate: 10.0
    command_publish_rate: 10.0

/**/digital_io_controller:
  ros__parameters:
    io_names:
      - digital_io_0
      - digital_io_1
    command_interfaces:
      - command
    state_interfaces:
      - state
    state_publish_rate: 10.0
    command_publish_rate: 10.0

/**/analog_io_controller:
  ros__parameters:
    io_names:
      - analog_io_0
      - analog_io_1
    command_interfaces:
      - command
    state_interfaces:
      - state
    state_publish_rate: 10.0
    command_publish_rate: 10.0
