# Use of /** so that the configurations hold for controller
# managers regardless of their namespace. Usefull in multi-robot setups.
/**/controller_manager:
  ros__parameters:
    update_rate: 1000

    # ROS 2 control broadcasters
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    force_torque_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    # LBR ROS 2 control broadcasters
    lbr_state_broadcaster:
      type: lbr_ros2_control/LBRStateBroadcaster

    # ROS 2 control controllers
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_position_controller:
      type: position_controllers/JointGroupPositionController

    # LBR ROS 2 control controllers
    lbr_joint_position_command_controller:
      type: lbr_ros2_control/LBRJointPositionCommandController

    lbr_torque_command_controller:
      type: lbr_ros2_control/LBRTorqueCommandController

    lbr_wrench_command_controller:
      type: lbr_ros2_control/LBRWrenchCommandController

    # Admittance controller
    admittance_controller:
      type: lbr_ros2_control/AdmittanceController

    # LBR IO Command Controller
    gpio_command_controller:
      type: gpio_controllers/GpioCommandController

    # LBR analog controllers
    lbr_analog_command_controller:
      type: lbr_ros2_control/LBRAnalogCommandController
    
    # LBR digital Command Controller
    lbr_digital_command_controller:
      type: lbr_ros2_control/LBRDigitalCommandController

/**/force_torque_broadcaster:
  ros__parameters:
    frame_id: lbr/link_tool # namespace: https://github.com/ros2/rviz/issues/1103
    sensor_name: estimated_ft_sensor

/**/joint_trajectory_controller:
  ros__parameters:
    joints:
      - A1
      - A2
      - A3
      - A4
      - A5
      - A6
      - A7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

/**/forward_position_controller:
  ros__parameters:
    joints:
      - A1
      - A2
      - A3
      - A4
      - A5
      - A6
      - A7
    interface_name: position

/**/gpio_command_controller:
  ros__parameters:
    gpios:
      - digital_io
      - analog_io
    command_interfaces:
      digital_io:
        - interfaces:
          - digital_io_1
          - digital_io_2
          - digital_io_3
          - digital_io_4
          - digital_io_5
          - digital_io_6
          - digital_io_7
          - digital_io_8
      analog_io:
        - interfaces:
          - analog_io_1
          - analog_io_2
    state_interfaces:
      digital_io:
        - interfaces:
          - digital_io_1
          - digital_io_2
          - digital_io_3
          - digital_io_4
          - digital_io_5
          - digital_io_6
          - digital_io_7
          - digital_io_8
      analog_io:
        - interfaces:
          - analog_io_1
          - analog_io_2
