name: build-ubuntu-24.04-fri-1.16
on:
  pull_request:
    branches:
      - jazzy
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-24.04
      fri_version: 1.16
