name: ubuntu-24.04-fri-1.15
on:
  pull_request:
    branches:
      - rolling
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-24.04
      fri_version: 1.15
